name: PR Checks

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify PR contents
    # Skip verification for dependabot PRs
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Check Title
        id: verifier
        uses: konveyor/release-tools/cmd/verify-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
